const val KOTLIN_VERSION = "1.3.10"
const val KOTLIN_COROUTINES_VERSION = "1.0.1"
const val KOTLIN_MOCKITO_VERSION = "2.0.0-RC1"
const val KLUENT_VERSION = "1.43"
const val JUNIT_VERSION = "4.12"

const val ANDROIDX_APPCOMPAT_VERSION = "1.0.2"
const val ANDROIDX_KTX_VERSION = "1.0.1"
const val ANDROIDX_CONSTRAINTLAYOUT_VERSION = "2.0.0-alpha2"

const val GOOGLE_MATERIAL_VERSION = "1.0.0"
